### ISSUE TITLE
게임 페이지 퍼블리싱

### ISSUE THREAD

**Issue by TransparentDeveloper** [2023-chambit-project/KOOSMOOS#24]
figma를 참고하여 갤러리 페이지를 퍼블리싱합니다.

[figma/KOOSMOOS/GamePage](https://www.figma.com/file/IbFxmTs2oEivZRf20gdy5u/KoosMoos?type=design&node-id=90-172&mode=design&t=mIVtrR66vKJx99LD-0)

**Comment by Doeunnkimm** [comment]
게임2 페이지 - 게임 다시 하러가기 버튼 누르면 스크롤 위치를 최상단으로 되도록 로직 추가하기
